# Change these first
owner: dd3tech # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: DD360 Landing page
    url: https://dd360.mx
  - name: Buildd3r Landing page
    url: https://dd360.mx
  - name: BUI Documentation
    url: https://bui.dd360.mx
  - name: DD360 WEB APP (Core)
    url: https://app.dd360.mx
  - name: Onboarding WEB APP
    url: https://onboarding.dd360.mx


status-website:
  themeUrl: https://raw.githubusercontent.com/dd3tech/status-page/master/assets/new-dark.css
  cname: status.dd360.mx
  logoUrl: https://onboarding.dd360.mx/assets/darkLogo.eaf6fea3.svg
  name: DD360
  introTitle: "**DD360** a status page to check services"
  introMessage: Check all our systems
  navbar:
    - title: Main website
      href: https://dd360.mx/
