owner: dd3tech
repo: status-page

sites:
  - name: DD360 Landing page
    url: https://dd360.mx

  - name: Buildd3r Landing page
    url: https://dd360.mx

  - name: BUI Documentation
    url: https://bui.dd360.mx

  - name: DD360 WEB APP (Core)
    url: https://app.dd360.mx

  - name: Onboarding WEB APP
    url: https://onboarding.dd360.mx

  - name: API's - Business
    url: $API_URL/business/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Loans
    url: $API_URL/loans/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Projects
    url: $API_URL/projects/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Onboarding
    url: $API_URL/onboarding/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Accounts
    url: $API_URL/accounts/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Documents
    url: $API_URL/documents/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Financial model
    url: $API_URL/financial-model/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Sales expenses
    url: $API_URL/sales-expenses/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Async
    url: $API_URL/async/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Developers
    url: $API_URL/developers/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Integrations
    url: $API_URL/integrations/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Users
    url: $API_URL/management/health
    method: GET
    expectedStatusCodes:
      - 200

  - name: API's - Seduvi
    url: $API_URL/seduvi/health
    method: GET
    expectedStatusCodes:
      - 200


status-website:
  favicon: https://cdn.statically.io/gh/dd3tech/status-page/master/assets/favicon.ico
  themeUrl: https://cdn.statically.io/gh/dd3tech/status-page/master/assets/new-dark.css
  cname: status.dd360.mx
  logoUrl: https://onboarding.dd360.mx/assets/darkLogo.eaf6fea3.svg
  name: DD360 Status
  introTitle: "Below, you can review the list of our monitored systems"
  introMessage: Check all our systems
  navbar:
    - title: Main website
      href: https://dd360.mx/
    - title: BUI
      href: https://bui.dd360.mx/
    - title: Onboarding
      href: https://onboarding.dd360.mx/

i18n:
  footer: Copyright © DD360